Moved logic for empty check earlier

diff --git a/nutrition_titan/dircertprep b/nutrition_titan/dircertprep
--- a/nutrition_titan/dircertprep
+++ b/nutrition_titan/dircertprep
@@ -59,6 +59,19 @@ then
 	tr '\t' ',' < dircertcombined.txt >> $COMBINEDFILE
 fi
 
+###Check for empty file
+if ([ ! -e *.csv ] && [ ! -e *.txt ])
+then
+	#Stop, cleanup, log, finish
+	echo "+ NO FILES DOWNLOADED!!!" >> $LOG
+	echo "+ Finshed " >> $LOG
+	echo "" >> $LOG
+	echo "------------------" >> $LOG
+	#Email and exit
+	python3 /usr/local/bin/mailsend.py "$TOEMAIL" "$SUBJECT_EMPTY" "$LOG"
+    exit 111
+
+
 ###Drop Title Lines 
 sed -i '/District,,,/d' $COMBINEDFILE
 sed -i '/School Year/d' $COMBINEDFILE
